### ISSUE TITLE
Search for Updates

### ISSUE THREAD

**Issue by SimonIT** [lineageos-infra/updater#18]
When I search on my LG G3 with the LineageOS build 14.1-20180410-nightly-d855 for updates I got an error that the updater couldn't search for updates and I should check my internet connection.
This is the exception which appears in adb:
```
04-16 22:51:55.051 15411-15411/org.lineageos.updater D/UpdatesActivity: Checking https://download.lineageos.org/api/v1/d855/nightly/a556d30458
04-16 22:51:55.847 15411-15411/org.lineageos.updater D/UpdatesActivity: List downloaded
04-16 22:51:55.847 15411-15411/org.lineageos.updater D/UpdatesActivity: Adding remote updates
04-16 22:51:55.855 15411-15411/org.lineageos.updater D/Utils: lineage-14.1-20180321-nightly-d855-signed.zip is older than current build
04-16 22:51:55.855 15411-15411/org.lineageos.updater D/Utils: Ignoring incompatible update lineage-14.1-20180321-nightly-d855-signed.zip
04-16 22:51:55.855 15411-15411/org.lineageos.updater D/Utils: lineage-14.1-20180328-nightly-d855-signed.zip is older than current build
04-16 22:51:55.855 15411-15411/org.lineageos.updater D/Utils: Ignoring incompatible update lineage-14.1-20180328-nightly-d855-signed.zip
04-16 22:51:55.856 15411-15411/org.lineageos.updater D/Utils: lineage-14.1-20180404-nightly-d855-signed.zip is older than current build
04-16 22:51:55.856 15411-15411/org.lineageos.updater D/Utils: Ignoring incompatible update lineage-14.1-20180404-nightly-d855-signed.zip
04-16 22:51:55.856 15411-15411/org.lineageos.updater D/Utils: lineage-14.1-20180410-nightly-d855-signed.zip is older than current build
04-16 22:51:55.856 15411-15411/org.lineageos.updater D/Utils: Ignoring incompatible update lineage-14.1-20180410-nightly-d855-signed.zip
04-16 22:51:55.882 15411-15411/org.lineageos.updater E/UpdatesActivity: Could not read json
                                                                        org.json.JSONException: End of input at character 0 of 
                                                                            at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
                                                                            at org.json.JSONTokener.nextValue(JSONTokener.java:97)
                                                                            at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                            at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                            at org.lineageos.updater.misc.Utils.parseJson(Utils.java:125)
                                                                            at org.lineageos.updater.misc.Utils.checkForNewUpdates(Utils.java:201)
                                                                            at org.lineageos.updater.UpdatesActivity.processNewJson(UpdatesActivity.java:306)
                                                                            at org.lineageos.updater.UpdatesActivity.-wrap2(UpdatesActivity.java)
                                                                            at org.lineageos.updater.UpdatesActivity$4.-org_lineageos_updater_UpdatesActivity$4_lambda$3(UpdatesActivity.java:345)
                                                                            at org.lineageos.updater.UpdatesActivity$4$-void_onSuccess_java_io_File_destination_LambdaImpl0.run(UpdatesActivity.java)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
04-16 22:52:54.737 15411-15411/org.lineageos.updater D/UpdaterService: Service no longer needed, stopping
```

But if there is an update, it is displayed and I can download it, so the main function is working.

**Comment by zifnab06** [comment]
Did you mean to close this or was this still an issue?

**Comment by SimonIT** [comment]
It's still an issue, but I thought it's the wrong place to report it
